services:
  - type: web
    name: zeiterfassung-render
    env: python
    plan: free
    buildCommand: |
      echo "🚀 Starting complete rebuild..."
      pip install -r requirements.txt
      echo "✅ Python dependencies installed"
      echo "📦 Installing Node.js for frontend build..."
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      echo "🔨 Building frontend..."
      cd frontend && npm install && npm run build && cd ..
      echo "📁 Copying build files..."
      cp -r frontend/build/* static/
      echo "✅ Build completed successfully!"
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: CLIENT_ID
        value: your-client-id-here
      - key: CLIENT_SECRET
        value: your-client-secret-here 