name: Container Deploy to Azure

on:
  push:
    branches: [ main ]  # anpassen, wenn ihr eine andere Haupt-Branch nutzt

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (für Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Build frontend (falls vorhanden)
        run: |
          if [ -f frontend/package.json ]; then
            cd frontend
            npm ci
            npm run build
            cd ..
          else
            echo "Kein frontend/package.json gefunden, überspringe Frontend-Build."
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}          # z.B. zeiterfassungacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}                  # nur wenn nicht Managed Identity
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        env:
          IMAGE_NAME: "${{ secrets.ACR_LOGIN_SERVER }}/zeiterfassung-app"
          TAG: "$(date +%Y%m%d%H%M)-${{ github.sha::7 }}"
        run: |
          IMAGE="${IMAGE_NAME}:${TAG}"
          echo "Baue Image $IMAGE"
          docker build --build-arg NODE_ENV=production -t "$IMAGE" .
          docker push "$IMAGE"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Web App to use new container image
        run: |
          IMAGE="${{ steps.build-and-push.outputs.image }}"
          echo "Setze Container Image auf Web App: $IMAGE"
          az webapp config container set \
            --resource-group la-zeiterfassung-rg \
            --name la-zeiterfassung-fyd4cge3d9e3cac4 \
            --docker-custom-image-name "$IMAGE" \
            --docker-registry-server-url "https://${{ secrets.ACR_LOGIN_SERVER }}"
          az webapp restart --resource-group la-zeiterfassung-rg --name la-zeiterfassung-fyd4cge3d9e3cac4 