name: Deploy to Azure Web App (ZIP)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Build frontend
        run: |
          if [ -f frontend/package.json ]; then
            cd frontend
            npm ci
            npm run build
            cd ..
          fi

      - name: Package app
        run: |
          zip -r app.zip app.py requirements.txt backend/ >/dev/null || true
          if [ -d frontend/build ]; then
            # Copy frontend build to static folder
            cp -r frontend/build/* static/
            zip -r app.zip static/ >/dev/null
          fi

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ZIP
        run: |
          az webapp deployment source config-zip \
            --resource-group la-zeiterfassung-rg \
            --name la-zeiterfassung-fyd4cge3d9e3cac4 \
            --src app.zip

      - name: Health check
        run: |
          sleep 10
          curl -I https://la-zeiterfassung-fyd4cge3d9e3cac4.azurewebsites.net/health || true
