"""Initial database schema

Revision ID: 0681613eee69
Revises: 
Create Date: 2025-08-04 00:21:08.748918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0681613eee69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('break_start', sa.DateTime(), nullable=True),
    sa.Column('break_end', sa.DateTime(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('regular_hours', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'BREAK', name='timeentrystatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_id'), 'time_entries', ['id'], unique=False)
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('break_start', sa.String(), nullable=True),
    sa.Column('break_end', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_schedules_id'), 'work_schedules', ['id'], unique=False)
    op.drop_table('zeiterfassung')
    op.add_column('daily_reports', sa.Column('materials_used', sa.Text(), nullable=True))
    op.add_column('daily_reports', sa.Column('issues_encountered', sa.Text(), nullable=True))
    op.add_column('daily_reports', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('daily_reports', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('daily_reports', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('daily_reports', 'date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('daily_reports', 'hours_worked',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('daily_reports', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reportstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('daily_reports', 'approved_by',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'approved_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    op.create_foreign_key(None, 'daily_reports', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'daily_reports', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'daily_reports', 'users', ['approved_by'], ['id'])
    op.add_column('orders', sa.Column('estimated_hours', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('actual_hours', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('orders', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('orders', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'assigned'"))
    op.alter_column('orders', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='orderpriority'),
               existing_nullable=True,
               existing_server_default=sa.text("'normal'"))
    op.alter_column('orders', 'assigned_to',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('orders', 'assigned_date',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('orders', 'completed_date',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['assigned_to'], ['id'])
    op.add_column('sick_leaves', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('sick_leaves', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('sick_leaves', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('sick_leaves', 'start_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sick_leaves', 'end_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sick_leaves', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='vacationstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('sick_leaves', 'approved_by',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('sick_leaves', 'approved_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('sick_leaves', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_sick_leaves_id'), 'sick_leaves', ['id'], unique=False)
    op.create_foreign_key(None, 'sick_leaves', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sick_leaves', 'users', ['approved_by'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('vacation_requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('vacation_requests', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('vacation_requests', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('vacation_requests', 'start_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('vacation_requests', 'end_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('vacation_requests', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='vacationstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('vacation_requests', 'approved_by',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('vacation_requests', 'approved_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('vacation_requests', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_vacation_requests_id'), 'vacation_requests', ['id'], unique=False)
    op.create_foreign_key(None, 'vacation_requests', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'vacation_requests', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacation_requests', type_='foreignkey')
    op.drop_constraint(None, 'vacation_requests', type_='foreignkey')
    op.drop_index(op.f('ix_vacation_requests_id'), table_name='vacation_requests')
    op.alter_column('vacation_requests', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('vacation_requests', 'approved_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vacation_requests', 'approved_by',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vacation_requests', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='vacationstatus'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('vacation_requests', 'end_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vacation_requests', 'start_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vacation_requests', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vacation_requests', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('vacation_requests', 'updated_at')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'sick_leaves', type_='foreignkey')
    op.drop_constraint(None, 'sick_leaves', type_='foreignkey')
    op.drop_index(op.f('ix_sick_leaves_id'), table_name='sick_leaves')
    op.alter_column('sick_leaves', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('sick_leaves', 'approved_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sick_leaves', 'approved_by',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sick_leaves', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='vacationstatus'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('sick_leaves', 'end_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sick_leaves', 'start_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sick_leaves', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sick_leaves', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('sick_leaves', 'updated_at')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('orders', 'completed_date',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'assigned_date',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'assigned_to',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('orders', 'priority',
               existing_type=sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='orderpriority'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'normal'"))
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'assigned'"))
    op.alter_column('orders', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('orders', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'actual_hours')
    op.drop_column('orders', 'estimated_hours')
    op.drop_constraint(None, 'daily_reports', type_='foreignkey')
    op.drop_constraint(None, 'daily_reports', type_='foreignkey')
    op.drop_constraint(None, 'daily_reports', type_='foreignkey')
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.alter_column('daily_reports', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('daily_reports', 'approved_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'approved_by',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reportstatus'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('daily_reports', 'hours_worked',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('daily_reports', 'date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('daily_reports', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('daily_reports', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('daily_reports', 'updated_at')
    op.drop_column('daily_reports', 'issues_encountered')
    op.drop_column('daily_reports', 'materials_used')
    op.create_table('zeiterfassung',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.Column('clock_in', sa.TEXT(), nullable=True),
    sa.Column('clock_out', sa.TEXT(), nullable=True),
    sa.Column('total_hours', sa.REAL(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('break_start', sa.TEXT(), nullable=True),
    sa.Column('break_end', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_work_schedules_id'), table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index(op.f('ix_time_entries_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
